name: Jason Maley Photography
favicon: null
layout_spectrum: 0.39085
typography_spectrum: 0.8646695262286812
title: Jason Maley Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.07465319475159049
  lightness: 0.06239382759667933
  saturation: 0.7133180028758943
  rhythmicContrast: 0.5566114427056164
purpose: []
